project:
  type: website
  output-dir: docs

format:
  html:
    toc: true
    toc-title: Contents
    toc-location: right
    linkcolor: "green"
    theme: 
      - zephyr
      - custom.scss
website:
  navbar:
    search: true
    title: >
      Mapeos_Comunitarios
    background: "primary"
  page-footer: 
    border: false
    background: dark
    foreground: "#ffffff"
    left: >
      Created by Gibran Mena-Aguilar
    center:
      - icon: github
        href: https://github.com/GibranMena
      - icon: envelope
        href: mailto:gibran@datacritica.org
    right: >
        [Powered by Quarto](https://quarto.org/)

